name: Build and draft GitHub release
description: Create TS/Node executable with vercel/pkg and release as compressed Zip file
# https://github.com/product-os/flowzone/tree/master/.github/actions
inputs:
  json:
    description: "JSON stringified object containing all the inputs from the calling workflow"
    required: true
  secrets:
    description: "JSON stringified object containing all the secrets from the calling workflow"
    required: true
  # --- custom environment
  NODE_VERSION:
    type: string
    default: "18.x"

runs:
  # https://docs.github.com/en/actions/creating-actions/creating-a-composite-action
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@1a4442cacd436585916779262731d5b162bc6ec7 # v3
      with:
        node-version: ${{ inputs.NODE_VERSION }}
        cache: npm

    - name: Install additional tools
      if: runner.os == 'Windows'
      shell: bash
      run: |
        choco install 7zip yq

    # https://github.com/product-os/scripts/tree/master/shared
    # https://github.com/product-os/balena-concourse/blob/master/pipelines/github-events/template.yml
    # node-gyp fails often, so retry on failure.
    # e.g. https://stackoverflow.com/questions/17967546/common-gypi-not-found-error-in-node-js
    # Limited error checking for commands; however will fail if can't find executable for 7z
    - name: Package release
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        npm install
        if (!$?) {
          echo "npm install failure; clear node-gyp cache and retry"
          sleep 10    # allow time for any clean up
          rm -Recurse -Force ${env:LOCALAPPDATA}\node-gyp\Cache
          npm install
        }
        # workaround exclusion of drivelist compiled module
        rm node_modules\pkg\dictionary\drivelist.js
        npm run build
        if (!(Test-Path "node_modules\drivelist\build\Release\drivelist.node")) {
          Write-Error "drivelist.node not found"
          Exit 1
        }
        npm run pkg

        # Download required WiFiProfileManagement Powershell module v1.1, and copy 
        # into expected 'modules' subdirectory for release. Use 'dist' directory 
        # since we need to include migrator binary from there anyway.
        cd dist
        set WFPM_COMMIT "c061bc1812a599baf572dc01bc6de077456b8b18"
        Start-BitsTransfer -Source https://github.com/jcwalker/WiFiProfileManagement/archive/${WFPM_COMMIT}.zip -Destination wfpm.zip
        7z x wfpm.zip
        # Remove zip so we don't include it in release.
        rm wfpm.zip
        mkdir modules
        move WiFiProfileManagement-${WFPM_COMMIT} modules\WiFiProfileManagement

        set version "v$(yq e '.[0].version' ..\.versionbot\CHANGELOG.yml)"
        7z a migrator-${version}-windows-x64.zip migrator.exe modules

    - name: Upload artifacts
      uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4
      with:
        name: gh-release-${{ github.event.pull_request.head.sha || github.event.head_commit.id }}-${{ strategy.job-index }}
        path: dist/*.zip
        retention-days: 1

